# ExampleMod 的标签，用作 Blowdryer（Spotless 等）设置版本，留空则禁用。
gtnh.settings.blowdryerTag = 0.2.2

# 若设置，RetroFutura/GTNH 构建逻辑将使用此发布版本号，而不是从 git 推导。
RELEASE_VERSION = 0.1.0

# 人类可读的模组名称，用于填充 mcmod.info。
modName = GTPerfectOverclock

# 区分大小写的标识符，用于填充 mcmod.info，并用于自动生成 mixin JSON。
# 惯例为小写。
modId = gtpoc

# 模组的根包名，用于在其他属性中查找各种类、
# mcmod.info 替换、在 run 任务中启用断言等。
modGroup = com.lelqwq.gtpoc

# 是否使用 modGroup 作为 Maven 发布的 group。
# 为 false 时使用 com.github.GTNewHorizons。
useModGroupForPublishing = true

# 有可用更新时自动更新你的 build.gradle 和 settings.gradle。
autoUpdateBuildScript = false

# 目标 Minecraft 版本
minecraftVersion = 1.7.10

# 目标 Minecraft Forge 版本
forgeVersion = 10.13.4.1614

# 指定依赖反混淆和 deobfParams 任务所用的 MCP 通道。
channel = stable

# 指定依赖反混淆和 deobfParams 任务所用的 MCP 映射版本。
mappingsVersion = 12

# 定义其他用于依赖反混淆的 MCP 映射。
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

# 选择测试模组时的默认用户名。可以每次运行覆盖，例如执行
# `./gradlew runClient --username=AnotherPlayer`，或在 IDE 中配置此命令。
developmentEnvironmentUserName = Developer

# 启用现代 Java 语法支持。合法值：
# - false: 无现代语法，仅 Java 8
# - jabel: Jabel 仅语法支持，编译为 J8 字节码
enableModernJavaSyntax = jabel

# 启用向反编译源码注入缺失的泛型，以获得更好的编码体验。
enableGenericInjection = true

# 生成一个类，其中包含如下定义的模组版本 String 字段。
# 若 generateGradleTokenClass 为空或未设置，则不生成此类。
generateGradleTokenClass = com.lelqwq.gtpoc.Tags

# 要生成/替换的、包含项目当前版本的 token 名称。
gradleTokenVersion = VERSION

# 若启用则提供 Mixin 设置。
usesMixins = true

# 指定包含所有 Mixin 的包（相对于 modGroup 的路径）。该包必须存在，否则
# 构建将失败。如果你的 mixins.<modid>.json 中定义了 package 属性，
# 它必须与 modGroup + 本值一致，否则构建将失败。
mixinsPackage = mixins

# 如果你的项目仅是 mixin 或核心模组的整合体，且不包含"普通"模组（= 某个
# 带有 @Mod 注解的类），请将此设为 true。拿不准时保持 false！
containsMixinsAndOrCoreModOnly = false

# 添加 CurseMaven、Modrinth 以及一些更知名的 1.7.10 仓库。
includeWellKnownRepositories = true

# 如果想发布到自定义 Maven 仓库（而非默认的 GTNH Maven），请将此处改为你的 Maven 坐标。
usesMavenPublishing = true

# 非 GTNH 属性
org.gradle.configuration-cache = true
org.gradle.parallel = true

# 禁用 GTNH 的 gitVersion 模块，使构建优先使用 RELEASE_VERSION
gtnh.modules.gitVersion = false
modVersion = 0.1.0
